name: Deploy Quantum AI API to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build & Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/quantum-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy quantum-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/quantum-api \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
